trigger:
  branches:
    include:
      - main

parameters:
- name: environment
  type: string
  default: dev
  values:
  - dev
  - qa
  - prod

pool: ce-agent


stages:

- stage: Validate
  jobs:
  - job: TerraformChecks

    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - script: |
        cd environments/${{ parameters.environment }}

        terraform init -backend=false

        terraform fmt -check -recursive

        terraform validate
      displayName: Terraform Validate

    - script: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        tflint --init
        tflint
      displayName: TFLint

    - script: |
        curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
        tfsec .
      displayName: TFSEC

- stage: Plan
  dependsOn: Validate

  jobs:
  - job: TerraformPlan

    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - script: |
        cd environments/${{ parameters.environment }}

        terraform init

        terraform plan \
          -var-file=terraform.tfvars
      displayName: Terraform Plan